### ISSUE TITLE
Aggiornamento a Bootstrap Italia 2.0

### ISSUE THREAD

**Issue by mluigi** [italia/design-django-theme#11]
Ci sarà l'aggiornamento a Bootstrap Italia 2.0?
Per ora ho provato a settare il CDN a `https://cdn.jsdelivr.net/npm/bootstrap-italia@2.0.2/dist/js/` e la maggior parte delle cose sembra funzionare. Gli unici problemi vengono dati da un riferimento alla libreria owl.carousel.js, che da quanto ho visto non viene più utilizzata, e dal caricamento da CDN di `sprite.svg`.

**Comment by francesco-filicetti** [comment]
Ciao @mluigi ,
si, subito dopo le vacanze estive verrà rilasciato l'aggiornamento a Bootstrap Italia 2.
Per gli attuali bug riscontrati sui file statici segnalati puoi aprire una PR.
Grazie del contributo

**Comment by francesco-filicetti** [comment]
Ciao @mluigi,
la versione 2.0.2 della libreria è stata rilasciata.
Il file sprite.svg nella nuova versione di Bootstrap Italia è stato rinominato in sprites.svg.
OWL Carousel non è più incluso nel bundle.

**Comment by mluigi** [comment]
Ciao @francesco-filicetti,
Riapro la issue poiché nella release non sono stati inclusi le cartelle `templates`, `templatetags` e `static`.

**Comment by francesco-filicetti** [comment]
@mluigi si, un errore nel file MANIFEST :)
ho rilasciato la v2.0.2-2 .
vai

**Comment by mluigi** [comment]
Sto effettuando la migrazione alla nuova versione e ho riscontrato due problemi nella parte dei form:

1. l'input `select` non viene mostrato correttamente, bisogna cambiare la classe al widget `BootstrapItaliaSelectWidget` da `bootstrap-select-wrapper` a `select-wrapper`
2. c'è un problema con le label degli input di testo che non vengono animate quando si inserisce un dato e rimangono quindi nel campo, ho risolto spostando l'inclusione dello script `bootstrap-italia.bundle.min.js` dall'head alla fine del body nel template di base
Ho creato la pull request #12 per risolvere questi 2 problemi.

**Comment by francesco-filicetti** [comment]
PR accettata con piacere.
Grazie

**Comment by simodalla** [comment]
Sto effettuando anche io la migrazione alla nuova versione ed il template di base bootstrap-italia-base.html ed i menu di tipo dropdown richiedono l'aggiunta della classe "dropdown-item" come da [documentazione](https://italia.github.io/bootstrap-italia/docs/componenti/dropdown/).

Ho creato la pull request #13 per risolvere la problematicha nel templte di esempio per i 2 menù: selettore della lingua ed "Esempio di dropdown".

Nello stesso template bootstrap-italia-base.html dovrebbe rimanere da sistemare "Esempio di Megamenu".
