### ISSUE TITLE
Dipendenze SASS

### ISSUE THREAD

**Issue by mdavino** [italia/design-django-theme#15]
PROPOSTA: 
Poiché il supporto SASS è facoltativo, non sarebbe il caso di rimuovere le dipendenze libsass e django-sass-processor dal setup.py?
Vale lo stesso per la dipendenza django_compressor.

**Comment by francesco-filicetti** [comment]
Ciao @mdavino,
assolutamente si.
Nei prossimi giorni effettuo il rilascio relativo alla nuova versione di Bootstrap Italia e contestualmente elimino le dipendenze.
Grazie!

**Comment by francesco-filicetti** [comment]
https://github.com/italia/design-django-theme/releases/tag/v2.3.6
