### ISSUE TITLE
Font errato

### ISSUE THREAD

**Issue by lallulli** [italia/design-django-theme#18]
L'attuale versione 2.3.6.post2 di design-django-theme non carica e non utilizza il font di Bootstrap Italia è Titillium. Nella scheda Network degli strumenti di sviluppo del browser non compare alcuna richiesta che fa riferimento al font Titillium.

Ho creato un nuovo progetto con Django 4.2, con una sola app vuota, e ho importato django-design-theme come indicato nel README. Ho copiato il template `base.html` di esempio, rimuovendo l'uso di stile custom con SASS.

La pagina risultante mi sembra avere due problemi:
- il font utilizzato non è Titillium
- nel footer, lo stile dell'elemento `h3` "Sezione link utili" è incorretto; il testo appare nero e allineato male.

Ho provato a caricare le risorse sia in locale (tramite file statici Django), sia tramite CDN. Il risultato non cambia. Ho fatto i test utilizzando sia Firefox che Chromium, con Manjaro Linux.

Ecco uno screenshot:

![image](https://user-images.githubusercontent.com/548413/231391175-488e68b2-3606-4afd-a857-3a02a04d930f.png)

Grazie per il vostro utilissimo lavoro!

**Comment by francesco-filicetti** [comment]
Ciao @lallulli ,
grazie infinite del tuo contributo.
Con la v2.3.6post2 il problema in realtà dovrebbe essere risolto perchè è stata integrata la breaking change che definisce il path dei font.
Fatto il collectstatic ?
Se vuoi appena possibile ci sentiamo/vediamo

**Comment by lallulli** [comment]
Ciao @francesco-filicetti grazie mille per la veloce risposta!
In effetti stavo utilizzando la v2.3.6post1 (installata ieri pomeriggio), ho aggiornato alla post2 e il problema del font è risolto.

Adesso rimane solo il problema dell'heading "Sezione Link Utili" formattato male.

**Comment by lallulli** [comment]
Confermo la risoluzione. Grazie mille di nuovo!
