### ISSUE TITLE
 Django 5

### ISSUE THREAD

**Issue by LorenzoProd** [italia/design-django-theme#19]
Sto utilizzando design-django-theme 2.8.2 con django 5.0.1, il che non soddisfa le dipendenze definite. Non ho notato incompatibilità. 
Qualcuno ci ha già lavorato? Semplicemente si potrebbe aggiornare la dipendenza?

**Comment by francesco-filicetti** [comment]
Ciao @LorenzoProd ,
non ho ancora utilizzato Django 5 e non ho analizzato eventuali breaking changes.
Se mi confermi che fila tutto liscio aggiorno volentieri la dipendenza :)
Grazie

**Comment by LorenzoProd** [comment]
@francesco-filicetti ti confermo che non ho problemi :)
Grazie

**Comment by francesco-filicetti** [comment]
https://github.com/italia/design-django-theme/commit/b5525ef9a0ebbb3a93cdc5dfb8bafe2a3aff6617
