### ISSUE TITLE
Update Bootstrap Italia integration

### ISSUE THREAD

**Issue by libremente** [italia/design-django-theme#3]
Ad oggi, l'ultima versione disponibile di Bootstrap Italia è la [1.2.6](https://github.com/italia/bootstrap-italia/releases/tag/v1.2.6). Siccome dalla versione `1.0.1` sono stati applicati diversi bugfix e sono state introdotte nuove features, sarebbe opportuno aggiornare il `base theme` all'ultima versione.
Grazie molte!
@francesco-filicetti 
cc @francescozaia

**Comment by peppelinux** [comment]
Questo avanzamento lo abbiamo programmato per la seconda settimana di Giugno 2019, dopo il rilascio di una piattaforma che attualmente lo utilizza. Mergeremo testando su questa eppoi il push sul  master branch. 

Grazie per la notifica e a presto

**Comment by libremente** [comment]
Perfetto, grazie! :+1:

**Comment by francescozaia** [comment]
Se avete dubbi, taggatemi pure qui o scrivetemi su Slack. La modifica principale è probabilmente la rimozione della chiamata per ottenere i font da Google Fonts, che invece ora devono essere caricati da locale, nel rispetto della privacy dei cittadini, come descritto qui: https://italia.github.io/bootstrap-italia/docs/come-iniziare/introduzione/#fonts.
Sono cambiate inoltre alcune cose nei form, ma spero non abbiano grande impatto.

**Comment by libremente** [comment]
Magari dopo aver fatto questa modifica possiamo anche fare una release così si popola la pagina dei packages di Django @peppelinux @francesco-filicetti

**Comment by peppelinux** [comment]
Hai ragione, dovremmo iniziare a taggare gli avanzamenti...
:+1:

**Comment by francesco-filicetti** [comment]
Ciao,
design-django-theme ora si basa su bootstrap-italia v.1.2.11 .
A presto

Il giorno lun 20 mag 2019 alle ore 15:14 Giuseppe De Marco <
notifications@github.com> ha scritto:

**Comment by libremente** [comment]
Perfetto, grazie mille @francesco-filicetti @peppelinux! Chiudo.

**Comment by peppelinux** [comment]
Grazie @francesco-filicetti
