### ISSUE TITLE
Proposal: add this project to Django Packages

### ISSUE THREAD

**Issue by libremente** [italia/design-django-theme#4]
I think it would be good to add this project to the [Django Packages](https://djangopackages.org/) to improve visibility and usability. 
What do you think?
If we decide to do so, I can go through the process of adding the package.
Thank you! :smile: 

@francesco-filicetti @francescozaia

**Comment by libremente** [comment]
@francesco-filicetti any update on this? What should we do?

**Comment by peppelinux** [comment]
Consider It done, Just Need some more time

**Comment by peppelinux** [comment]
Done here
https://djangopackages.org/packages/p/design-django-theme/
thanx for the hint
