### ISSUE TITLE
Problema con django-debug-toolbar

### ISSUE THREAD

**Issue by paolodina** [italia/design-django-theme#7]
Buongiorio, ho notato che se è installato design-django-theme non funziona django-debug-toolbar. Quando clicco su uno dei pannelli della toolbar ottengo questo errore in console:
```
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at Object.visible (toolbar.js:25)
    at HTMLAnchorElement.<anonymous> (toolbar.js:72)
    at HTMLUListElement.<anonymous> (toolbar.js:7)
```
Se commento `bootstrap_italia_template` in `INSTALLED_APPS` la toolbar funziona. Inoltre, anche tenendola installata, il problema non si verifica sulle pagine dell'admin (ma solo sui template di frontend).

Capita anche a voi? E come si può risolvere? Grazie.

**Comment by peppelinux** [comment]
Ciao Paolo,

effettivamente non usiamo django-debug-toolbar.
Temo che il js di bootstrap italia, non modificato da noi, collida con questo.
Lascio questa issue aperta come riferimento a questa esigenza che altri utilizzatori di django-debug-toolbar possono maturare con questo progetto, alcontempo posso dirti che questa integrazione non è prevista nella nostra roadmap e se tu volessi "spingerla" dentro siamo ben disposti ad accettare da te eventuali pull request,
Grazie per averci avvisato

**Comment by paolodina** [comment]
followup, sembrerebbe proprio che l'anomalia fosse nella toolbar, https://github.com/jazzband/django-debug-toolbar/issues/1261

**Comment by peppelinux** [comment]
Grazie per avercelo notificato. Facci sapere quando e se credi che questa issue possa essere chiusa, a presto

**Comment by paolodina** [comment]
Per ora la lascerei aperta per un motivo, nel repo della debug toolbar c'è un project di esempio, l'ho fatto girare e la toolbar funziona... Per ora per me è un mistero, quando ne so qualcosa in più vediamo cosa fare con il ticket. Grazie!

**Comment by paolodina** [comment]
a questo punto chiuderei il ticket. l'ideale sarebbe che sistemassero la cosa upstream sul repo della debug toolbar ma nel frattempo... mi accontento del workaround quick and dirty
